site_file: /Users/quinn/Dropbox (VTFRS)/Research/EFI_RCN/NOAA_GEFS_container/example/noaa_download_site_list_test.csv
downscale: TRUE
run_parallel: TRUE
overwrite: FALSE
num_cores: 2
forecast_date: all
forecast_time: all
